#!/usr/bin/python3

#example for loops

def Range():
	for rangeNum in range(5):

            print(rangeNum)

def ForList():
    for listVal in ['a','b','c','d']:
        print(listVal)

Range()
ForList()



